services:
    prometheus:
        image: prom/prometheus:latest
        ports:
          - "9090:9090"
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
          - prom_data:/prometheus 
        command: "--config.file=/etc/prometheus/prometheus.yml"

    grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin 
        - GF_SECURITY_ADMIN_PASSWORD=grafana 
      volumes:
        - grafana_data:/var/lib/grafana
    service:
      image: flask-app:latest
      ports:
        - "8080:8080"
        
volumes:
  prom_data:
  grafana_data:
